### ISSUE TITLE
API versioning?

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#105]
On our last call, @mrunalk mentioned that a fix for #12 is coming soon.  So I'm wondering about API versioning.  

API endpoint paths have what appears to be a version number:

```
http GET https://api.rollbar.com/api/1/team/689492/projects
```

When the new endpoint for deleting access tokens is released, will the API version be incremented?  Will it use [semver](https://semver.org/)?

@coryvirok

**Comment by coryvirok** [comment]
We haven't been very good about versioning for the API. So, the fix for #12 will not change the version number, no. Our next major API version will be better at implementing semver.
