### ISSUE TITLE
Clarification on notification endpoints

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#110]
I want to make sure I understand correctly how the notifications system works.  @mrunalk @coryvirok Please let me know if I understand this correctly:

The "configuring integration" endpoint - e.g. `PUT /api/1/notifications/email` - turns _all_ email notifications on or off, depending on the value of `enabled` in the payload.  But it does not actually cause any notifications to be sent.

The "setup rules" endpoint - e.g. `PUT /api/1/notifications/email/rules` - controls the actual notifications that are sent.

**Comment by coryvirok** [comment]
@jondeandres can you help answer these questions since you worked on this API?

**Comment by jondeandres** [comment]
@jmcvetta you are right. `enabled` is a property of the integration while each channel can have configured different rules, those rules are setup through `PUT /api/1/notifications/:integration/rules`.

Each integration might have different allowed triggers and each trigger allows different filters on them. I guess you are following https://explorer.docs.rollbar.com/#tag/Notifications, you can see there the different triggers/filters allowed per integration

**Comment by jmcvetta** [comment]
Cool.  

So that raises the question of how (and whether) to make Terraform control integration `enabled` status.  

Terraform likes to think in terms of _resources_ that can be created and destroyed. E.g. we can create a team and later delete that team.  Or we can even take the ID of an existing team and import it, to bring that team under Terraform control.  

But channel `enabled` status is a toggle - it always has either one or the other state.  So let's say we create a `rollbar_slack_integration` resource:

```hcl
resource "rollbar_slack_integration" "foo" {
  service_account_id = 1234567
  channel = "foobar"
  enabled = true
}
```

Seems straight forward.  But what happens when we destroy this resource?  Does it revert to `enabled = false`?  But what if the `enabled` status was `true` before the `rollbar_slack_integration` resource was ever created?  Is the resource supposed to remember the prior state? That doesn't seem right either.

One option is for Terraform to assume that if you have defined notification rules for a given channel, you must want that channel enabled.  But is that a safe assumption?  I doubt it.  

Another option is for Terraform not to touch channel enabled status.  But then we can't use Terraform by itself to setup notifications.  

Maybe - _maybe_ - the best option is to revert to unmanaged when the integration resource is destroyed.  In this case, when a `rollbar_slack_integration` resource is created, Terraform will make sure that `enabled` is set to the value configured for that resource.  And when the resource is destroyed, Terraform will do nothing and simply stop caring about that integration.

**Comment by jmcvetta** [comment]
Another thing we must consider and document is that Terraform [does not have any means to create a singleton resource](https://discuss.hashicorp.com/t/singleton-resource/9869) - a resource for which there can be only one instance.  

So if a user were to create two `rollbar_slack_integration` resources with different arguments, Terraform will allow this, and one of the two will be permanently out of sync with the API.  Apparently the canonical solution to this problem is to document it and hope the TF developer reads the docs.

**Comment by jondeandres** [comment]
> One option is for Terraform to assume that if you have defined notification rules for a given channel, you must want that channel enabled. But is that a safe assumption? I doubt it.

We've seen in the past scenarios where a customer wanted to disable completely the integration without removing the rules, usually because of flooding them somehow.

> 
> Another option is for Terraform not to touch channel enabled status. But then we can't use Terraform by itself to setup notifications.
> 
> Maybe - _maybe_ - the best option is to revert to unmanaged when the integration resource is destroyed. In this case, when a `rollbar_slack_integration` resource is created, Terraform will make sure that `enabled` is set to the value configured for that resource. And when the resource is destroyed, Terraform will do nothing and simply stop caring about that integration.

Can we document that if a `rollbar_slack_integration` wants to be destroyed correctly the way to do it would be setting `enabled = false` first and then remove the resource?

One question, a `DELETE /api/1/notifications/:integration/` API would help? What it's expected by you to have?

The reasoning behind having always `PUT  /api/1/notifications/:integration/` was that "the integration already exists for the project but it needs to be configured" so it didn't make sense for us to use `POST` and `DELETE` methods. But I think the `DELETE` method on an integration is quite convenient, so it wouldn't be a bad idea implementing it.

**Comment by jmcvetta** [comment]
> Can we document that if a `rollbar_slack_integration` wants to be destroyed correctly the way to do it would be setting `enabled = false` first and then remove the resource?

Consider this scenario:  

A developer already has 10 manually-configured notification rules in Rollbar, created through the web UI.  Then he starts using Terraform.  He adds 5 TF-managed rules, but doesn't touch his 10 original rules.  And he adds a `rollbar_slack_integration` resource - even tho Slack integration was already enabled for his original rules.  

At some point the dev decides he no longer needs the new set of rules - the set that is managed by TF.  So he runs `terraform destroy` to remove them all.  And it destroys the `rollbar_slack_integration` too.  But I'm gonna guess the dev does _not_ want Slack integration toggled to `enabled=false`.  Because that would shut down his manually-configured rules.

**Comment by jmcvetta** [comment]
> One question, a `DELETE /api/1/notifications/:integration/` API would help? What it's expected by you to have?

What I really need are the endpoints described in #111.  The second item in the bullet list, to list all rules, would be super nice to have; but isn't strictly necessary.  The others are the minimum API support needed to allow Terraform to control Rollbar notifications.

**Comment by jmcvetta** [comment]
I notice now that we need a _project_ access token when enabling an integration channel.  Does that mean that integrations are enabled for that project only?  

So if we define multiple `rollbar_project` resources, we'll also need a matching number of `rollbar_notifications_slack_integration` resources?

**Comment by phillipuniverse** [comment]
@rollbar-bborsits I see this is closed, what is the resolution?
