### ISSUE TITLE
Notifications and project access tokens

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#112]
Creating a [notification rule](https://explorer.docs.rollbar.com/#tag/Notifications) requires a project access token, _not_ an account access token.  The payload for creating a notification rule does not have any reference to a project ID.  

So I'm assuming the notification is linked to a project based on the project access token used to create it?

If that's the case, there are (at least) two ways we can handle it:

### Manually managed token

The Terraform developer defines a project; defines a project access token with "write" scope linked to that project; and defines a notification rule linked to that token.

Advantage: explicit
Disadvantage: verbose

```hcl
resource "rollbar_project" "test" {
  name = "tf-acc-test-example-1"
}

resource "rollbar_project_access_token" "write_token" {
  name = "test-write-token"
  project_id = rollbar_project.test.id
  scopes = ["write"]
}

resource "rollbar_notification_email" "foo" {
  token_id = rollbar_project_access_token.write_token.id

  rule {
    trigger = "new_item"
    environment_filter {
      operation = "eq"
      value = "foobar"
    }
  }
  
}
```

### System default token

User defines a project.  Instead of automagically deleting the project's default tokens as in #75, we keep the default `write` scope token.  Then use this token only for creating notifications.  

Advantage: Less boilerplate.  
Disadvantage: Excessively _magical_ - conceals underlying infrastructure.

```hcl
resource "rollbar_project" "test" {
  name = "tf-acc-test-example-1"
}

resource "rollbar_notification_email" "foo" {
  project_id = rollbar_project.test.id

  rule {
    trigger = "new_item"
    environment_filter {
      operation = "eq"
      value = "foobar"
    }
  }

}
```

## Account access token

Preferred to either of these approaches is that described in #62, allowing creation of notifications using an account access token rather than a project access token.

@mrunalk @coryvirok

**Comment by coryvirok** [comment]
Until we get #62 implemented, let's go with the explicit and verbose option. Thanks!
