### ISSUE TITLE
Is Slack channel really optional in config for Slack notification rule?

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#114]
In the API docs for the `config` payload when setting up a Slack notification rule, the Slack channel is not shown as `required`.  Is this actually correct?  If no channel is specified, where do the notification go?  @mrunalk @jondeandres 

![image](https://user-images.githubusercontent.com/55682/99225948-7e1d2780-281b-11eb-96ea-2b8d193a2e86.png)

**Comment by jondeandres** [comment]
@jmcvetta in case of Slack, you can see that the channel itself has a required `channel` property. If a rule configuration doesn't have a `channel` property we'll use the channel's default to send the messages

**Comment by jmcvetta** [comment]
:+1: Gotcha.  If no channel is specified in the rule, it uses the default channel set by the "configuring integration" endpoint.
