### ISSUE TITLE
Terraform syntax for Rollbar notification rules

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#115]
I'm thinking about whether notification rules for different alert channels should be different Terraform resources; or whether they should be combined into a single resource.  

I'm leaning toward a combined resource, but I would like to know your throughts.  @coryvirok @mrunalk @jondeandres 

## Separate resources per channel

Advantage: Closely follows the underlying API
Disadvantage: Repetitive if we configure the same notification rule for different channels

```hcl
resource "rollbar_notification_email" "foo" {

  token_id = rollbar_project_access_token.write_token.id

  rule {
    trigger = "new_item"
    environment_filter {
      operation = "eq"
      value = "foo"
    }
  }

  config {
    users = ["somedev@somecompany.com"]
  }

}

resource "rollbar_notification_slack" "foo" {

  token_id = rollbar_project_access_token.write_token.id

  rule {
    trigger = "new_item"
    environment_filter {
      operation = "eq"
      value = "foo"
    }
  }

  config {
    channel = "rollbar"
  }

}
```

## Combined resource

Advantage: More convenient and less repetitive when we want the same notification rule to alert different channels
Disadvantage: Does not closely follow underlying API

```hcl
resource "rollbar_notification" "foo" {

  token_id = rollbar_project_access_token.write_token.id

  rule {
    trigger = "new_item"
    environment_filter {
      operation = "eq"
      value = "foo"
    }
  }

  email {
    users = ["somedev@somecompany.com"]
  }

  slack {
    channel = "rollbar"
  }
}
```

**Comment by jondeandres** [comment]
@jmcvetta it'd be great if that's doable, but I am not sure that'll fit the product as it is right now.

At the end a "new item" rule is a combination of:

- A generic rule for a `new_item` trigger
- Some specific properties for every channel's rule

Example:

We define in our Open Spec API definition a "new item email rule" as:


```
    NewItemEmailRule:
      type: object
      allOf:
        - $ref: '#/components/schemas/NewItemRule'
        - $ref: '#/components/schemas/EmailRuleConfig'
```

Where `NewItemRule` is a generic representation for "new item rule" which is:

```
    NewItemRule:
      type: object
      required:
        - trigger
      properties:
        trigger:
          type: string
          enum: ['new_item']
          description: An error/ message is seen for the first time
        filters:
          type: array
          description: To keep your notifications relevant, you'll want to apply filters to limit when they send messages or create incidents.
          items:
            anyOf:
              - $ref: "#/components/schemas/environment_filter"
              - $ref: '#/components/schemas/level_filter'
              - $ref: '#/components/schemas/title_filter'
              - $ref: '#/components/schemas/filename_filter'
              - $ref: '#/components/schemas/context_filter'
              - $ref: '#/components/schemas/method_filter'
              - $ref: '#/components/schemas/framework_filter'
              - $ref: '#/components/schemas/path_filter'
              - $ref: '#/components/schemas/path_filter_with_exists'
```

But each email rule has its specific properties through `EmailRuleConfig`:

```
    EmailRuleConfig:
      type: object
      properties:
        config:
          type: object
          properties:
            teams:
              type: array
              description: List of team names to send emails to
            users:
              type: array
              description: List of usernames or email addresses to send emails to
```

As you can see, in summary, every rule is combined with the generic properties of that rule type but also specific properties of each channel. So I think we'd need a different resource definition on each channel in terraform too.

**Comment by jmcvetta** [comment]
The combined resource syntax is good _if_ users often like to configure the same notification to be sent on multiple channels.  The combined syntax avoids having a bunch of copypasta in your TF configuration; or needing to do something complicated like a user defined module.  But it does not reflect the current API, and (probably?!) does not reflect the underlying database.  

It's _possible_ to create a synthetic TF resource - i.e. a resource that does not have a 1:1 relationship with an entity on the API.  We're doing this with the `rollbar_user` resource, as discussed in #87.  It's definitely a lot more complicated than a normal TF resource.  Is it worth it / a good idea here?

What's feasible and desirable here may depend a lot on the database structure behind the API, and the roadmap for its future.  Is a _notification rule_ one wide table, with a column for every field and sub-field described in the API?  Or is a _notification rule_ a narrow table with mostly foreign key columns?

Any implementation of a TF resource for notification rules will require some additions/changes to the API.  The underlying database structure will probably determine whether those additions/changes are easy or difficult to make.

**Comment by hiimbex** [comment]
Don't have a big opinion on approach here, but wanted to say +1 to requesting this feature. My team would love to manage our rollbar notifications -- especially our grouping & filters since they've gotten more complex lately -- via terraform.

**Comment by Limess** [comment]
We've basically given up on managing rollbar notifications without this feature in a tool like terraform - manually doing things is painful and the we don't really want to plumb in our own service to manipulate these via API for each new service. Would love to see this out
