### ISSUE TITLE
API support for deleting project access token

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#12]
Currently the API does not support deleting a project access token.  This functionality is required for the Terraform provider to manage project access tokens.

```
$ http DELETE https://api.rollbar.com/api/1/project/411334/access_token/d6d4b456f72048dfb8a933afe3ac66f6 X-Rollbar-Access-Token:redacted
HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Alt-Svc: clear
Content-Length: 40
Content-Type: application/json; charset=utf-8
Date: Tue, 06 Oct 2020 11:48:58 GMT
Server: nginx/1.17.9
Via: 1.1 google
X-Response-Time: 1ms

{
    "err": 1,
    "message": "not found"
}
```

**Comment by jmcvetta** [comment]
@mrunalk @coryvirok  

Is this a good place to open Issues for API feature requests / bugs / etc?  Or is there another repo that would be better?

**Comment by coryvirok** [comment]
This should work for now. I'll link to it in our internal tracking system.

**Comment by mrunalk** [comment]
You should be able to delete project access token now. I haven't updated the API doc yet will do that soon.
