### ISSUE TITLE
Automated publishing to Terraform registry

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#153]
Per #57, once the key is setup, we need to update the Github Actions workflow to add automated publishing of Releases to the Terraform Registry.

~Blocked by #152, #151, #150.~

**Comment by jmcvetta** [comment]
Automated release build is working through Github Actions.

**Comment by jmcvetta** [comment]
However I am not able to setup publishing on Terraform Registry.  Probably because I do not have sufficient permissions on Rollbar's Github Organization.  

![image](https://user-images.githubusercontent.com/55682/101906783-1d9bc300-3bec-11eb-8e3f-48043d59ccd6.png)

It looks like the TF Registry app _does_ have permission on the Github org.

![image](https://user-images.githubusercontent.com/55682/101907098-a3b80980-3bec-11eb-885c-2c996cc4d1d6.png)

@coryvirok I think you are the only admin for the Github Organization.  Can you please set up publishing?  [The docs](https://www.terraform.io/docs/registry/providers/publishing.html#publishing-your-provider) don't give much insight to what will be involved in setting it up.

**Comment by coryvirok** [comment]
Looks like TF is still not able to verify the builds due to missing SHASUMS file. Their instructions here say to use their GitHub action to generate the necessary files:

https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-
https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.goreleaser.yml#L36

**Comment by jmcvetta** [comment]
This should be fixed in release v1.0.1.

**Comment by jmcvetta** [comment]
Provider is published to the registry.

**Comment by jmcvetta** [comment]
Confirmed on v1.0.2: when a new release is created by semantic-release, it is automatically published to the Terraform Registry.
