### ISSUE TITLE
resourceUserDelete does not delete user

### ISSUE THREAD

**Issue by awendt** [rollbar/terraform-provider-rollbar#226]
Hi! 👋🏻 

I noticed that deleting the user resource only removed the user from the teams, but not from the account. The implementation of `resourceUserDelete` is currently:

1. get user ID
2. get current teams
3. remove user from current teams
4. done

Is it intention that the user resource is not deleted?

**Comment by GreyOBox** [comment]
@awendt 
https://github.com/rollbar/terraform-provider-rollbar/pull/231
It has to help

**Comment by davidji99** [comment]
@awendt

My take is that `rollbar_user` should be renamed to something else. The current name implies that I can manage the lifecycle of a user in Rollbar. This is incorrect. `rollbar_user` only manages the association of a user with a team.

Furthermore, there is only `GET` support for the https://explorer.docs.rollbar.com/#tag/Users.
