### ISSUE TITLE
API returns deleted projects

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#23]
After deleting a project through the API, it still shows up in the list of projects returned by the API - only with its name set to nil. This seemingly undesirable behavior should be fixed on the API side. We [work around it](https://github.com/rollbar/terraform-provider-rollbar/blob/a1b8356f3628ae4c30412818678b278d23d1848a/client/project.go#L96-L108) by removing any result with an empty name.

This does not seem like desirable behavior for the API.  Once a project has been deleted, the API should not include it in the list or projects.

**Comment by jmcvetta** [comment]
We see this behavior expressed several ways:  

The list of projects returned by `GET /api/1/projects` includes projects that have been deleted.  

The deleted projects have their `name` field set to `null`.  The deleted projects have a somewhat different set of fields than non-deleted projects.  The fields are mostly blank; those fields that are populated may be full of bogus data.  

A call to `GET /api/1/project/{projectId}` will return `200 OK` status and the same bogus project data structure.  

## Desired behavior

* List projects should not return deleted projects.
* Get project for a deleted project ID should return a HTTP status `404 Not Found`.

**Comment by jmcvetta** [comment]
API will list access tokens for deleted projects:

```
# Project delete suceeds
$ http DELETE https://api.rollbar.com/api/1/project/412646/access_tokens X-Rollbar-Access-Token:redacted

{
  "err": 0
}


# Current expected behavior for a deleted project
$ http GET https://api.rollbar.com/api/1/project/412646 X-Rollbar-Access-Token:redacted  | grep name
    "name": null


# We can still list project access tokens for the deleted project.
$ http GET https://api.rollbar.com/api/1/project/412646/access_tokens X-Rollbar-Access-Token:redacted

{
  "err": 0,
  "result": [
    {
      "project_id": 412646,
      "access_token": "2b4f4180c8814c519577889faf80c9db",
      "name": "post_server_item",
      "status": "enabled",
      "rate_limit_window_size": null,
      "rate_limit_window_count": null,
      "cur_rate_limit_window_start": null,
      "cur_rate_limit_window_count": null,
      "date_created": 1602495301,
      "date_modified": 1602495301,
      "scopes": [
        "post_server_item"
      ]
    },
    {
      "project_id": 412646,
      "access_token": "38eb9ceaca24408088d7f5ea0059dc90",
      "name": "post_client_item",
      "status": "enabled",
      "rate_limit_window_size": null,
      "rate_limit_window_count": null,
      "cur_rate_limit_window_start": null,
      "cur_rate_limit_window_count": null,
      "date_created": 1602495301,
      "date_modified": 1602495301,
      "scopes": [
        "post_client_item"
      ]
    },
    {
      "project_id": 412646,
      "access_token": "b320e4c7ca5d4171876ad95e3c05c4bd",
      "name": "write",
      "status": "enabled",
      "rate_limit_window_size": null,
      "rate_limit_window_count": null,
      "cur_rate_limit_window_start": null,
      "cur_rate_limit_window_count": null,
      "date_created": 1602495301,
      "date_modified": 1602495301,
      "scopes": [
        "write"
      ]
    },
    {
      "project_id": 412646,
      "access_token": "fb15423a455548b4afca410effdf968b",
      "name": "read",
      "status": "enabled",
      "rate_limit_window_size": null,
      "rate_limit_window_count": null,
      "cur_rate_limit_window_start": null,
      "cur_rate_limit_window_count": null,
      "date_created": 1602495301,
      "date_modified": 1602495301,
      "scopes": [
        "read"
      ]
    }
  ]
}

**Comment by mrunalk** [comment]
After investigating this I think this is intentional as I see there is a way to restore a deleted project. If someone accidentally deletes a project, there should be a way to restore that project. To restore a project one needs a project id. Maybe you can check if "status" is "enabled" for active projects otherwise they are deleted or can be ignored. @coryvirok, correct me if I'm wrong.

**Comment by jmcvetta** [comment]
If the behavior is intentional, there is probably a better way to implement it.  Consider these results, showing 1 deleted project and 1 active project:

```json
{
  "err": 0,
  "result": [
    {
      "id": 411692,
      "account_id": 317418,
      "settings_data": {
        "integrations": {
          "jira": {},
          "clubhouse": {},
          "bitbucket": {},
          "github": {},
          "trello": {},
          "slack": {},
          "datadog": {},
          "pagerduty": {},
          "gitlab": {},
          "webhook": {},
          "victorops": {},
          "ciscospark": {},
          "asana": {},
          "pivotal": {},
          "campfire": {},
          "azuredevops": {},
          "sprintly": {},
          "hipchat": {},
          "lightstep": {},
          "email": {},
          "flowdock": {}
        },
        "grouping": {
          "auto_upgrade": true,
          "recent_versions": [
            "5.0.0"
          ]
        }
      },
      "date_created": 1602083693,
      "date_modified": 1602083695,
      "name": null
    },
    {
      "id": 411704,
      "account_id": 317418,
      "status": "enabled",
      "settings_data": {
        "grouping": {
          "auto_upgrade": true,
          "recent_versions": [
            "5.0.0"
          ]
        }
      },
      "date_created": 1602085345,
      "date_modified": 1602085345,
      "name": "foo"
    }
  ]
}
```

The active project returns a field `"status": "enabled"`.  So we would expect the deleted project to return a field `"status": "disabled"`.  But it does not.  It does not return any `status` field at all.

Instead the deleted project's name is set to `null`.  That makes the data not very useful for restoring a project, since we don't know which project it was.

**Comment by jmcvetta** [comment]
Another thing to consider...  The most recent time I ran the acceptance tests, listing all projects returned 756 items, of which only 4 were active valid projects.  So the API is pumping out ton of useless data just to get the small amount of useful data.  See `raw_projects` and `cleaned_projects` in the debug log below.

```
{"level":"debug","url":"https://api.rollbar.com/api/1/projects","raw_projects":756,"cleaned_projects":4,"time":"2020-10-15T18:59:20+07:00","caller":"/home/jmcvetta/projects/terraform-provider-rollbar/client/project.go:109","message":"Successfully listed projects"}
```

The acceptance tests run on each push to Github.  So the total number of deleted projects is going to keep climbing and climbing.  Each deleted case that's sent over the wire increases database load, CPU load, and network usage.  And the data really has no utility at all, because a) the API doesn't currently have an "undelete" endpoint; and b) the project names are stripped out, so they're just anonymous ID numbers.

**Comment by coryvirok** [comment]
Looks like this is actually a bug in our API since it shouldn't return deleted projects. Ideally, we can support returning soft deleted projects by passing in a "deleted=true" or something similar. 

@mrunalk can you file a story internally to fix that in the API and maybe a second to implement the option to return deleted projects?

**Comment by jmcvetta** [comment]
Any movement on this?  

As of right now, listing projects for my account returns 2985 projects.  100% of which are deleted.  

```
$ http GET https://api.rollbar.com/api/1/projects X-Rollbar-Access-Token:redacted | jq ' .result | length'
2985
```

**Comment by mrunalk** [comment]
@jmcvetta, plan to take this up next on my list after #12 is fixed.

**Comment by jmcvetta** [comment]
> plan to take this up next on my list after #12 is fixed

Awesome!

**Comment by jmcvetta** [comment]
I am no longer seeing deleted projects returned in the projects list.  @mrunalk are we good to close this ticket?

**Comment by ajtran** [comment]
Yes. @jmcvetta we can close this ticket. I've released the fix for this.
