### ISSUE TITLE
Open Pull Requests

### ISSUE THREAD

**Issue by Omicron7** [rollbar/terraform-provider-rollbar#254]
Hey there. Thanks for all the hard work you're all put into this provider.

Would it be possible to get some reviews and movement on the existing PR's? These add features and fix some of the bugs people are experiencing with large numbers of projects/users/teams.

* #229 
* #231 
* #250 
* #253 

I'd really like to use the official Rollbar provider and not need to fork and host our own in order to continue using terraform with Rollbar.

Thanks again.
- Brian

cc @bsxs @waltjones @pawelsz-rb @dbw0011

**Comment by jtsaito** [comment]
@bxsx  @waltjones @pawelsz-rb @dbw0011 Could you please provide an ETA for this issue. We are relying on some of the above PRs to be fixed.

**Comment by cyrusradfar** [comment]
Hi, 

I apologize for the delay. There was a lapse in a maintainer here, along with a few failures in the way we bring issues into our internal PM process. We are/have fixed those issues. 

Apologize for the abysmally slow response. Our community deserves better and we have a lot in mind to improve here. 

I'm supremely grateful for your patience and support. It's something I and the folks at Rollbar do not take lightly.

**Comment by cyrusradfar** [comment]
@Omicron7 I'm closing this out as all the tickets you've referred to are now merged.
