### ISSUE TITLE
How should provider handle `ErrNotFound`

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#26]
Per discussion with Cory on Slack, need to research if/how the provider can handle `ErrNotFound` returned by API client.

**Comment by jmcvetta** [comment]
The official Github provider handles 404 errors by [removing the item from state](https://github.com/terraform-providers/terraform-provider-github/blob/643cf2f06c98a7e8b061d8a06ae6b9bec0bf0deb/github/resource_github_team.go#L129-L134):

```go
			if ghErr.Response.StatusCode == http.StatusNotFound {
				log.Printf("[WARN] Removing team %s from state because it no longer exists in GitHub",
					d.Id())
				d.SetId("")
				return nil
			}
```

**Comment by coryvirok** [comment]
Maybe we can have the default behavior be to error out but we can provide an option to remove the item from the state?

**Comment by jmcvetta** [comment]
Provider should return a detailed `diag.Diagnostic` object.  Currently it uses `diag.FromErr()` to convert `ErrNotFound` to `Diagnostic` object.  This provides a bland, unhelpful error message to the Terraform user.

**Comment by jmcvetta** [comment]
Sending a diagnostic with severity Error probably isn't the right behavior.  It leaves Terraform wedged if a resource is deleted manually through the web UI.  It's not even possible to run `terraform destroy`.  Requiring the entity to be removed manually from TF state.

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.rollbar_projects.all: Refreshing state... [id=1603530866]
rollbar_project.test: Refreshing state... [id=417557]

Error: Project not found

Project 417557 not found

$ terraform destroy
data.rollbar_projects.all: Refreshing state... [id=1603530866]
rollbar_project.test: Refreshing state... [id=417557]

Error: Project not found

Project 417557 not found
```

**Comment by jmcvetta** [comment]
I'm thinking the Github provider's behavior is correct:  Remove the item from state, and emit a warning.  Since the item is already gone from the SaaS, Terraform can't actually do anything to manage it.  The best and only thing Terraform can do is recreate it.  Which is what will happen if we remove it from state.

**Comment by jmcvetta** [comment]
I _think_ it will be sufficient to handle `ErrNotFound` on the read functions of each resource.  Since Terraform always calls read before attempting to update or delete.
