### ISSUE TITLE
Support web hook integration as a resource

### ISSUE THREAD

**Issue by nieblara** [rollbar/terraform-provider-rollbar#313]
Let's add support to configure a web hook integration in our TF provider. 

https://docs.rollbar.com/reference/put_api-1-notifications-webhook

**Comment by ivan-sukhomlyn** [comment]
@nieblara @pawelsz-rb It will be perfect to have this functionality in the nearest releases. Thanks 🙂

**Comment by nieblara** [comment]
hi there @alinazabara and @ivan-sukhomlyn 
Enabling and disabling a slack integration is supported as of the latest release, here is an example

https://github.com/rollbar/terraform-provider-rollbar/blob/master/example/resources.tf#L89


As for the webhook integration support, that is on its way with the next release!
