### ISSUE TITLE
Setting timezone on project

### ISSUE THREAD

**Issue by Nikamura** [rollbar/terraform-provider-rollbar#334]
Hey, I would like to be able to set timezone of the project via terraform.

https://github.com/rollbar/terraform-provider-rollbar/blob/f06b02f44a0bc4614327058c3d93014fc11b5ed6/client/project.go#L73-L73

**Comment by rollbar-bborsits** [comment]
Hey @Nikamura, Thanks for your request. I'll add this item to the roadmap candidate list.
