### ISSUE TITLE
feature-request terraform resource for "rollbar_notification_enable"

### ISSUE THREAD

**Issue by dylan-shipwell** [rollbar/terraform-provider-rollbar#360]
when using `rollbar_notification` resources, [doc](https://registry.terraform.io/providers/rollbar/rollbar/latest/docs/resources/notification) 
an important detail to notice is 
> The notification channels are enabled and disabled through the Rollbar UI.

I would like to use terraform specifically to avoid manual configuration steps like this one, "click enable in the ui setting for every created project, -> notification integration"

Is terraform-provider-rollbar open to adding a `resource` type for enabling/disabling rollbar notifications?

I checked for an outstanding bug/issue and didn't find one, I read a little bit of #62 but this seemed unrelated to enabling notification integrations.

Thanks

**Comment by rollbar-bborsits** [comment]
Hey @dylan-shipwell, Thanks for reporting this feature request. The Rollbar Terraform provider cannot switch a notification on/off indeed. However, this would be a nice add-on to our config options, so I'll move this request to our idea backlog.

**Comment by phillipuniverse** [comment]
@rollbar-bborsits where is the "idea backlog"? How can we get visibility into the prioritization and plans for some of these issues?

**Comment by rollbar-bborsits** [comment]
@phillipuniverse It sits in our internal ticketing system for now. Currently, we're working on improving our product processes. We plan to create a public roadmap, but that takes some time until we get there.

**Comment by phillipuniverse** [comment]
>  We plan to create a public roadmap

@rollbar-bborsits well just my opinion but a good start might be to keep publicly-opened issues open until they get resolved!

**Comment by rollbar-bborsits** [comment]
@phillipuniverse Yeah, that might make sense. My thinking around the cleanup was that the issues around the SDKs have become very noisy lately. Sometimes I see very old tickets open that have become unrelated over the years, or they were just ideas never thought through really. I thought it'd help a lot if we should focus on what we can tackle in the near future and save the other requests to another place.
