### ISSUE TITLE
Does it make sense to expose current rate limit info?

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#52]
Does it even make sense for the Terraform provider to expose `cur_rate_limit_window_count` and `cur_rate_limit_window_start` as attributes on a `rollbar_project_access_token` resource?  These values should change constantly - so I don't see how they would be useful as Terraform outputs.  If anything, their presence as resource attributes may be confusing.

@coryvirok @mrunalk what are your thoughts?

**Comment by coryvirok** [comment]
I think it makes sense to keep these. They're helpful for rate limits that have a very long window, e.g. a month. Customers can use this information to understand how close to their monthly "budget" they are.

**Comment by jmcvetta** [comment]
Right now these are exposed in data sources `rollbar_project_access_token` and `rollbar_project_access_tokens`; but not in resource `rollbar_project_access_token`.  I will revisit this to see if it's feasible to expose this field in the resource too.

**Comment by jmcvetta** [comment]
Closed by PR #70
