### ISSUE TITLE
Publish provider

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#57]
https://www.terraform.io/docs/registry/providers/publishing.html

Blocked by #12.

**Comment by jmcvetta** [comment]
Blocked by #12 and #35.  We should not publish the provider until PAT behavior is as documented.

**Comment by jmcvetta** [comment]
In order to publish our provider on the Terraform Registry, we need to [create GPG a signing key](https://www.terraform.io/docs/registry/providers/publishing.html#preparing-and-adding-a-signing-key).  

This key should be stored somewhere secure that belongs to Rollbar - not on my personal computer.  @coryvirok Does Rollbar have a corporate LastPass or similar for secure storage of credentials?

**Comment by jmcvetta** [comment]
We'll also need someone who is an admin of the Rollbar Github organization to upload the signing key to the Terraform Registry.

![image](https://user-images.githubusercontent.com/55682/100340343-9bb57280-300d-11eb-91eb-948235b7733c.png)

**Comment by fmasuhr** [comment]
@jmcvetta We are really looking forward to this to use the default download via terraform registry. Do you already have an ETA?

**Comment by jmcvetta** [comment]
@fmasuhr I'm hoping to have the provider published to the Terraform Registry by next week.

Here's what's needed to proceed:

* [ ] Generate GPG signing key - @natesweet
* [ ] Store key in Rollbar.com corporate LastPass - @natesweet please let me know when we can expect these two items to be ready
* [ ] Add public key to Terraform Registry - @mrunalk are you an admin for the Rollbar Github Organization?
* [ ] Add private key and passphrase to this repo's Github Secrets, as documented [here](https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-) -  @jmcvetta 
* [ ] Update Github Actions workflow to add automated publishing of releases - @jmcvetta

**Comment by mrunalk** [comment]
@jmcvetta, completed first 3 tasks. Are you sure the Task#4 does not need this new private key and passphrase created along with this new GPG key?

**Comment by jmcvetta** [comment]
> Are you sure the Task#4 does not need this new private key and passphrase created along with this new GPG key

The private key for this task is the private half of the GPG key pair just created; and the passphrase (if any) required to use it.  The key will be used to sign the binaries built by the CI/CD system before they are uploaded to Terraform registry.  

@mrunalk I have added you as an admin on this repo.  You should have permission to [add the key to Github secrets](https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-).

**Comment by jmcvetta** [comment]
After merge of #189, release v1.0.0 has been published _on Github_.  To complete the publishing process, we still need to publish it to the Terraform Registry per #153.

**Comment by jmcvetta** [comment]
Provider is published to the registry.
