### ISSUE TITLE
Unexpected `from_user_id` on invitations created through API

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#63]
When I create a team invitation through the web UI, that invitation shows my correct Rollbar user ID in the `from_user_id` field.  However when I create an invitation through the API, it shows a different user ID (that does not belong to me).

It looks like maybe the invitation is recorded as coming from a special "API User" account, rather than the account that owns the token that authorized the API call.  

```
# My user ID
$ http GET https://api.rollbar.com/api/1/users X-Rollbar-Access-Token:redacted

{
    "err": 0,
    "result": {
        "users": [
            {
                "email": "jason.mcvetta@gmail.com",
                "id": 238101,
                "username": "jmcvetta"
            }
        ]
    }
}


# Invitation that was created through web UI
$ http GET https://api.rollbar.com/api/1/team/676971/invites X-Rollbar-Access-Token:redacted

{
    "err": 0,
    "result": [
        {
            "date_created": 1603192170,
            "date_redeemed": null,
            "from_user_id": 238101,
            "id": 153649,
            "status": "pending",
            "team_id": 676971,
            "to_email": "jason.mcvetta+test3@gmail.com"
        }
    ]
}


# Invitation created through the API
$ http POST https://api.rollbar.com/api/1/team/676971/invites X-Rollbar-Access-Token:redacted email:='"jason.mcvetta+test4@gmail.com"'

{
    "err": 0,
    "result": {
        "date_created": 1603192477,
        "date_redeemed": null,
        "from_user_id": 5325,
        "id": 153650,
        "status": "pending",
        "team_id": 676971,
        "to_email": "jason.mcvetta+test4@gmail.com"
    }
}

**Comment by jmcvetta** [comment]
Yup, there it is - user `sys:internalapi` created the invitation.

![image](https://user-images.githubusercontent.com/55682/96579569-45179300-1301-11eb-974b-e993048d922a.png)

**Comment by coryvirok** [comment]
We should probably change the UI to say this user was invited by the API or change the API to accept a `from_user_id`.

**Comment by ajtran** [comment]
We will proceed with not displaying the `sys:internalapi` in the UI and instead just display `the API` like so:

![image](https://user-images.githubusercontent.com/10730200/102129249-e869bd80-3e03-11eb-9dd3-f28ead1ca7c8.png)

And we will remove `from_user_id` from the API result if the invite is from an internal user.

**Comment by jmcvetta** [comment]
> We will proceed with not displaying the sys:internalapi in the UI and instead just display the API like so:

:+1: 

> And we will remove `from_user_id` from the API result if the invite is from an internal user.

Please don't remove this field.  An API endpoint should always return the same _shape_ of data, regardless of the data contents.  Maybe instead return a `from_user_id` field with a `null` value.

**Comment by ajtran** [comment]
> Please don't remove this field. An API endpoint should always return the same _shape_ of data, regardless of the data contents. Maybe instead return a `from_user_id` field with a `null` value.

Ah, alright! Understood. Can do and will do.

**Comment by ajtran** [comment]
This should be delivered in production.

**Comment by jmcvetta** [comment]
Confirmed this is working as expected on the API:

```
$ http GET https://api.rollbar.com/api/1/invite/161423 X-Rollbar-Access-Token:$ROLLBAR_API_KEY 
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Alt-Svc: clear
Content-Length: 230
Content-Type: application/json; charset=utf-8
Date: Fri, 18 Dec 2020 07:57:14 GMT
ETag: "-937845645"
Server: nginx/1.17.9
Via: 1.1 google
X-Rate-Limit-Limit: 5000
X-Rate-Limit-Remaining: 4999
X-Rate-Limit-Remaining-Seconds: 60
X-Rate-Limit-Reset: 1608278294
X-Response-Time: 21ms

{
    "err": 0,
    "result": {
        "date_created": 1608278161,
        "date_redeemed": null,
        "from_user_id": null,
        "id": 161423,
        "status": "pending",
        "team_id": 704936,
        "to_email": "jason.mcvetta+foo@gmail.com"
    }
}
```
