### ISSUE TITLE
Handle default access tokens in newly created project

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#67]
As part of project resource creation, the default project access tokens can be deleted, if an option is set on the project resource.

**Comment by jmcvetta** [comment]
Maybe the way to handle this is to make project access tokens into a [nested block](https://www.terraform.io/docs/configuration/syntax.html#arguments-and-blocks).  If the block is empty, create the default tokens.  If the block is populated, only create the tokens described in the block.

Buuuut...  I don't like that there is special magic going on.  It's not really _obvious_  what's happening.  Yes, we can document it; but it's unconventional.  The behavior could potentially be _surprising_ to users.  Surprising is not really a good thing in the ops world.

**Comment by jmcvetta** [comment]
A better way to handle this is to change the API's behavior.  I can't imagine too many users are going to opt for keeping the default unmanaged tokens.  The whole point of using Terraform is to have everything managed - your whole infrastructure is described in the Terraform config.  

@mrunalk @coryvirok  How feasible would it be to get an API enhancement, so there is a way to create a new project without automagically creating any access tokens?

In the mean time, I think the best behavior for the Terraform provider is to delete the default tokens immediately upon creating a new project.  So there are never unmanaged tokens attached to the project.  

I don't think setting a flag on the project's Terraform config is the right solution.  Every argument  in the Terraform config describes some aspect of the remote system's state that can be _managed_ by Terraform.  Meaning if I change `default_tokens = false` to `default_tokens = true`, on the next run Terraform needs to recreate the set of default tokens.  

That's a lot of code for functionality I don't think anyone will actually want to use.

**Comment by coryvirok** [comment]
Seems like the right approach is:

1. Short term, have the TF Provider delete default tokens
2. Medium term, provide the project creation API with an option to skip creation of the default tokens
3. Longer term, deprecate the API option to skip creation of the default tokens and replace it with an option to create default tokens, (i.e. flip the logic)

@mrunalk can you add an internal story for the API enhancements above? Thanks!

**Comment by jmcvetta** [comment]
Since the API currently has few users, would it be easier/better to skip step 2?  I doubt it would be any more difficult from a programming perspective to do (3) than to do (2).  Better to make significant changes while there are fewer users to be surprised or inconvenienced.  

But - I don't have usage data for the API, so I don't actually know how many are currently using it.

**Comment by jmcvetta** [comment]
PR #75 implemented the new behavior, deleting default tokens on project creation.  

**Note however:** the API does not yet support deleting project access tokens.  So the underlying calls made by the code just merged in #75 are no-ops.  They emit a warning message, but aren't actually able to delete anything.  

Issue #12, API support for deleting project access tokens, is a blocker here.  @mrunalk I hope we can have that feature soon.  It is my biggest need for support from the API team.
