### ISSUE TITLE
Reconcile API-only team properties with UI

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#7]
From the [API docs](https://explorer.docs.rollbar.com/#operation/create-a-team):

> `standard` is the only access level you can choose in the UI.
>
> `light` and `view` are API-only team access levels. `light` gives the team read and write access, but not to all settings. `view` gives the team read-only access.

I'm a little concerned about this, since the UI and the API may have different logic on the backend.  @mrunalk is it safe to use these API-only team access levels?

**Comment by mrunalk** [comment]
Good question. I don't know why there are different access_levels for API and UI. But I don't think using API-only access_level would be an issue.
