### ISSUE TITLE
`id` field for project access token

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#73]
Currently the API uses the access token itself is used as the identifier for a project access token object.  This is undesirable, as the token may be exposed in intermediary HTTP logs, as well as in debug logs.  

Instead the API should expose a standard integer `id` field to identify PAT objects.

**Comment by coryvirok** [comment]
This is likely a security issue on our end since access tokens might be the the PATH of incoming requests.
