### ISSUE TITLE
API returns `403 Forbidden` when team or project not found

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#79]
When trying to [read a team](https://explorer.docs.rollbar.com/#operation/get-a-team) with an ID that doesn't exist, the API returns status `403 Forbidden`.  Instead it should return `404 Not Found`.  

```
$ http GET https://api.rollbar.com/api/1/team/9999999999 X-Rollbar-Access-Token:redacted
HTTP/1.1 403 Forbidden
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Alt-Svc: clear
Content-Length: 62
Content-Type: application/json; charset=utf-8
Date: Mon, 26 Oct 2020 06:53:39 GMT
ETag: "1635533788"
Server: nginx/1.17.9
Via: 1.1 google
X-Rate-Limit-Limit: 5000
X-Rate-Limit-Remaining: 4998
X-Rate-Limit-Remaining-Seconds: 23
X-Rate-Limit-Reset: 1603695242
X-Response-Time: 13ms

{
    "err": 1,
    "message": "Team not found in this account."
}
```

**Comment by jmcvetta** [comment]
Same behavior when a project is not found.

**Comment by jmcvetta** [comment]
Interestingly, this bug does _not_ apply to project access tokens.

**Comment by jmcvetta** [comment]
After this issue is corrected in the API, the [workaround](https://github.com/rollbar/terraform-provider-rollbar/blob/ee3692320f3e1cd8006d8b739a28ad6dbc9256ae/client/client.go#L92-L103) should be removed from the `client` package.

**Comment by ajtran** [comment]
This should be resolved now. I've released a fix that returns 404 Not Found.

**Comment by jmcvetta** [comment]
Per https://github.com/rollbar/terraform-provider-rollbar/pull/198#issuecomment-771550375, it appears this issue is not yet fully resolved.

**Comment by ajtran** [comment]
Reopened and will close when https://github.com/rollbar/terraform-provider-rollbar/pull/198 is merged.

**Comment by jmcvetta** [comment]
Per @ajtran this has been fixed in prod API.  Confirmed by acceptance tests for #198.
