### ISSUE TITLE
Thinking about users

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#87]
I'm trying to figure out the right way for Terraform to control Rollbar users.  

On the Rollbar side, a user can't be created, only invited.  Users only exist in the context of a team - there is no concept of a user who is not a member of any team.  We create an invitation, and at some unspecified point in the future the recipient may (or may not) confirm their invitation and register as a user.  

On the Terraform side, the developer (who is writing the Terraform config) defines users who are members of one or more team.  When the developer runs `terraform apply`, Terraform runs some sequence of API commands and creates the users.  

Herein lies the challenge:  Terraform _can't_ actually create the users, because Rollbar users can only be invited not created.  Thus Terraform must think about a "user" as being one or the other of two related entities: an invitation, or an actual Rollbar user.  

Since we don't know the eventual Rollbar user ID when we send an invitation, we have to use the recipient's email as the primary identifier of the "user" in Terraform state.  

The challenge with this is there's no API endpoint to easily translate an email into a Rollbar user ID; or an endpoint go get all invitations for a given email.  It is possible, but inefficient, to translate email to user ID by reading the list of all users from the API.  It's likewise possible, but even less efficient, to get the list of all invitations for a user by reading all invitations from all groups.  

@coryvirok @mrunalk I'm eager to hear your thoughts on the best way to handle this.

**Comment by jmcvetta** [comment]
One thought is to combine Rollbar user ID and email for the terraform state ID.  Giving a TF state ID like `238101:jason.mcvetta@gmail.com`.  Invited but not yet registered users would have a TF state ID like `0:teammate@company.com`.  Then Terraform could prefer the Rollbar user ID when available; or do things the inefficient way when we only have an email.

But...  After the initial `terraform apply`, if nothing changes in the Terraform config and nothing is changed manually on Rollbar web U, subsequent runs of `terraform apply` should make no changes.  The Terraform state will not update.  

Meaning that the technique described above, would only capture the ID of the newly created Rollbar user _after_ something has changed in Terraform config.  Which may never happen.  

I need to research more:
* Is there any documented way it's valid for TF state to change when running `terraform plan` (the read step), but not running `terraform apply` (the write step)?  I don't think so, but it's possible.
* Best practices: How does AWS terraform provider handle invites for ACM certficates?

**Comment by jmcvetta** [comment]
Checked into how the AWS provider [handles ACM certificate requests](https://github.com/terraform-providers/terraform-provider-aws/blob/eec4f71c885788d86ca39b3f6e016ddcabcb75a0/aws/resource_aws_acm_certificate.go#L251-L289).  Turns out the AWS API creates an inactive certificate object when the call is made; that cert just doesn't become active until the domain owner confirms it.  Thus Terraform immediately has the ARN to use as identifier.

Looks like no useful best practices there that can be applied to our users & invitations.

**Comment by coryvirok** [comment]
The fact that the API cannot create users does make this challenging... 

What if we only stored the email address for a user on a team in the TF state? The provider would then check to see if the email was on the team, (i.e. there's a registered Rollbar user on the team and they have a user ID) *or* the email was invited to the team. In this scenario, the resource would be something like `TeamUser` or `TeamEmail`. Since invites need to be accepted by users and cannot be automated, the Provider would only care that the email address was invited or already exists on the team. This would also make it easier to work with other TF tools that don't have any concept of a Rollbar user, but they do understand email addresses.

Could that work?

**Comment by jmcvetta** [comment]
Sure, that could work.  

I'm taking that approach with [the current code](https://github.com/rollbar/terraform-provider-rollbar/blob/1592d3782be333f5f7167f036c4888bb0480ae5e/rollbar/resource_user.go#L98-L201).  But for it to be efficient, it needs some new API endpoints:
* Get user ID from email - #82 
* Get all teams for user, get all invitations for user - #88
