### ISSUE TITLE
Email address for acceptance testing

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#91]
Acceptance testing creates a _lot_ of team invitations.  Currently they're all going to my gmail account.  This is not ideal because it makes the testing infrastructure dependent on a resource that belongs to me not to Rollbar.

@coryvirok Can we get a rollbar.com email address for use with acceptance testing?

It would be super awesome if we could figure out a way to have some of those invitations programmatically accepted, so we can do automated testing on the full user lifecycle.

**Comment by jmcvetta** [comment]
Ideally we want a forwarding address.  Something like `terraform-acceptance-tests@rollbar.com`, that forwards to me and anyone else involved with maintaining the provider.

**Comment by coryvirok** [comment]
I created a group and added you to it. The address is `terraform-provider-test@rollbar.com`.

**Comment by jmcvetta** [comment]
The new address is not working.  

I received the response below to a test message sent from Protonmail.   However I received no response (and no forwarded message) when sending from my Gmail account.  

> Hello jmcvetta@protonmail.com,
> 
> We're writing to let you know that the group you tried to contact (terraform-provider-test) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
>  * You might have spelled or formatted the group name incorrectly.
>  * The owner of the group may have removed this group.
>  * You may need to join the group before receiving permission to post.
>  * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/rollbar.com/bin/topic.py?topic=25838.
> 
> Thanks,
> 
> rollbar.com admins

**Comment by jmcvetta** [comment]
Code is updated to use new email address in branch [`update-email-to-rollbar-address`](https://github.com/rollbar/terraform-provider-rollbar/tree/update-email-to-rollbar-address).  

However that branch cannot pass acceptance tests until I register terraform-provider-test@rollbar.com as a Rollbar user.  That can't happen until the new address is able to forward message to me.

**Comment by jmcvetta** [comment]
Please forward messages to jason.mcvetta@gmail.com, not to my Protonmail.
