### ISSUE TITLE
Programmatically confirm team invites during acceptance testing

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#92]
As mentioned in #91, we need a way to confirm emailed team invitations in order to run automatic acceptance tests over the entire gamut of `rollbar_user` functionality.  Because a Terraform `rollbar_user` resouce encompasses both invitations and users on the API.  

@coryvirok @mrunalk @jtsaito @fmasuhr Any thoughts on how to approach this?  There's probably an existing tool for the purpose, tho I haven't found it yet.

**Comment by jmcvetta** [comment]
In order to accept an invitation, a user must be logged in to Rollbar.com.  This may make it more difficult to automate.  

![image](https://user-images.githubusercontent.com/55682/97848044-1b0f9900-1d23-11eb-99c3-f6e0e6e54771.png)

**Comment by fmasuhr** [comment]
@jmcvetta We also encountered this issue when developing the provider but AFAIK did not found any workaround for it so far :(

**Comment by jmcvetta** [comment]
Thanks for the feedback @fmasuhr!

**Comment by jmcvetta** [comment]
We are able to do acceptance testing on both invited and registered users, with a manually-registered user for the latter.  

But without this Issue being resolved, we are _not_ able to test the transition from invited to registered.
